name: Build

permissions:
  contents: read
  statuses: write

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - staging

jobs:
  staging-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Run Build
        id: build
        run: npm run build
        continue-on-error: true

      - name: Set Build Status (Build Success)
        if: steps.build.outcome == 'success'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }}" \
            -d '{"state":"success", "description":"Build Succeeded", "context":"Build"}'

      - name: Set Build Status (Build Failure)
        if: steps.build.outcome != 'success'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }}" \
            -d '{"state":"failure", "description":"Build Failed", "context":"Build"}'
