name: Deploy to Server

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set target server based on branch
        id: set-server
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "SERVER_IP=${{ secrets.PRODUCTION_HOST }}" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            echo "SERVER_IP=${{ secrets.STAGING_HOST }}" >> $GITHUB_ENV
          else
            echo "Invalid branch"
            exit 1
          fi
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SHARED_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
      - name: Run deployment script on server
        run: |
          ssh ${{ secrets.STAGING_USER }}@$SERVER_IP "bash -c '
              cd /home/ubuntu/avoda-be/
              git pull
              /home/ubuntu/.nvm/versions/node/v22.14.0/bin/node /home/ubuntu/.nvm/versions/node/v22.14.0/bin/npm i
              /home/ubuntu/.nvm/versions/node/v22.14.0/bin/node /home/ubuntu/.nvm/versions/node/v22.14.0/bin/npm run build
              /home/ubuntu/.nvm/versions/node/v22.14.0/bin/node /home/ubuntu/.nvm/versions/node/v22.14.0/bin/pm2 restart 0
            '"
